### PR TITLE
Update from Intelsdi-x pluginsync 0.1.6

### PR DESCRIPTION
**Pull request by nanliu**

### CODE REVIEW

**Comment by nanliu** [comment]
The jenkins test is not passing yet, but travis is working at this point.

**Comment by kindermoumoute** [comment]
We should merge that first: https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/pull/78

**Comment by nanliu** [comment]
We verified Jenkins build is successful as well:
https://ci.snap-telemetry.io/job/snap-influxdb-integration-large-prb-k8s/6/

**Comment by kindermoumoute** [comment]
please test this

**Pull request merged**
