### PR TITLE
Renamed snapd to snapteld in a comment, corrected a comment

### PR DESCRIPTION
**Pull request by katarzyna-z**
Summary of changes:
- Renamed snapd/snapctl to snapteld/snaptel in README and comment

### CODE REVIEW

**Comment by lmroz** [comment]
I suggest holding on this, in https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/tree/master/examples/tasks there are scripts and readme referring to snapd/snapctl.

**Comment by katarzyna-z** [comment]
Large tests are updated in #93

**Comment by lmroz** [comment]
:ship:

**Comment by IzabellaRaulin** [comment]
LGTM

**Pull request merged**
