### PR TITLE
Updated plugin to use version 2 of the client

### PR DESCRIPTION
**Pull request by thomastaylor312**
I kept having some issues with the previous version of the plugin. So I tried it with the v2 client for Influx and I thought it might be helpful to merge the changes in since v1 is deprecated.

### CODE REVIEW

**Comment by thomastaylor312** [comment]
@geauxvirtual I saw you as the author of this plugin, but I am not sure who is the maintainer. Can you point me in the right direction?

**Comment by geauxvirtual** [comment]
Can you provide more information as to what version of Influx are you running the plugin against? I know v0.10.0 has been released, but I don't think we've updated the plugin or tested the plugin against v0.10.0 even though the client libraries got updated at some point.

**Comment by thomastaylor312** [comment]
I am running against v0.10.0, but the v2 client was also build to work with v0.9.X

**Comment by thomastaylor312** [comment]
@geauxvirtual I just got the integration tests working and they worked fine with v0.9. I also added support for v0.10.1 integration and it also passed.

**Comment by geauxvirtual** [comment]
Can you update the Godep to match the commit for 0.10.1 release. Then we'll need to see about the differences from this branch and a merge that happened last night to get them aligned.

**Comment by thomastaylor312** [comment]
Ok, I made sure the godep version was correct for Influx.

**Comment by thomastaylor312** [comment]
@geauxvirtual Any way we can take a look at this today? I am going to be unavailable to work on this for the next week. I can try rebasing in master and fixing the conflicts if you'd like.

**Comment by geauxvirtual** [comment]
Sure, I have time today to help look at this.

**Comment by thomastaylor312** [comment]
@geauxvirtual Had any ideas on what is making the integration tests fail with the `connection refused` error?

**Comment by geauxvirtual** [comment]
So far, I have not been able to figure this issue out unfortunately.

Justin Guidroz

**Comment by thomastaylor312** [comment]
@geauxvirtual I figured it out!!! It was a pain but it was a combination of a stupid error on my part with the v0.10 script and some race conditions. I think I have them ironed out and the build is working.

**Comment by thomastaylor312** [comment]
@geauxvirtual ping

**Comment by geauxvirtual** [comment]
LGTM. Merging this.

**Pull request merged**
