### PR TITLE
Fixes #49 - add support for latest snap metric type

### LINKED ISSUE #49: Add support for the latest snap metric type

### PR DESCRIPTION
**Pull request by jcooklin**

### CODE REVIEW

**Comment by mjbrender** [comment]
This diff is rough with vendoring. Reviewers can jump to the `influx.go` here: https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/pull/50/files#diff-52c62d9a3dca127212c6e5dcb77d2867

**Comment by geauxvirtual** [comment]
Why is the vendor directory added to this PR? We haven't vetted how we plan on using vendoring, nor what tool will be used to populate and maintain the vendor directory?

Justin Guidroz

**Comment by jcooklin** [comment]
>Why is the vendor directory added to this PR?

I feel there is more upside in using it than potential downsides.  

>We haven't vetted how we plan on using vendoring, nor what tool will be used to populate and maintain the vendor directory?

I would like to use a few plugins, this included, to validate godeps as the tool before suggesting it to be used for the rest of the plugins.  I've tested the workflow and think it works fine. 

`go get -u github.com/influxdata/influxdb`
`godep update github.com/influxdata/...`

Thoughts?

**Comment by jcooklin** [comment]
I removed vendoring from this PR.

**Pull request closed without merging**
