### PR TITLE
Update from Intelsdi-x pluginsync 0.1.5

### PR DESCRIPTION
**Pull request by nanliu**

### CODE REVIEW

**Comment by nanliu** [comment]
Previous PR omitted this release section of travis.

**Comment by candysmurf** [comment]
LGTM

**Comment by IRCody** [comment]
@candysmurf, @nanliu -- This is failing the large test. The local large tests is also failing for me with the same error? Not sure why yet though.

**Comment by kindermoumoute** [comment]
See #75

**Pull request merged**
